packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.5
  '@dotenvx/dotenvx': ^1.51.4
  '@formatjs/intl-localematcher': ^0.6.2
  '@orpc/client': ^1.11.2
  '@orpc/openapi': ^1.11.2
  '@orpc/server': ^1.11.2
  '@orpc/tanstack-query': ^1.11.2
  '@orpc/zod': ^1.11.2
  '@prisma/client': ^7.0.0
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tailwindcss/postcss': ^4.1.17
  '@tanstack/react-form': ^1.25.0
  '@tanstack/react-query': ^5.90.9
  '@tanstack/react-query-devtools': ^5.90.2
  '@types/negotiator': ^0.6.4
  '@types/node': ^22.19.1
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  babel-plugin-react-compiler: 19.1.0-rc.3
  better-auth: ^1.3.34
  dotenv: ^17.2.3
  lucide-react: ^0.553.0
  nanoid: ^5.1.6
  negotiator: ^1.0.0
  next: ^16.0.10
  prisma: ^7.0.0
  react: 19.2.1
  react-dom: 19.2.1
  sharp: ^0.34.5
  sonner: 2.0.7
  tailwindcss: ^4.1.17
  tsdown: ^0.16.4
  tsx: ^4.20.6
  turbo: ^2.6.1
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  zod: 4.1.12
  next-intl: ^4.5.6
  baseline-browser-mapping: ^2.8.32
  '@hookform/resolvers': ^5.2.2
  'react-hook-form': ^7.66.0
  pino: ^9.9.5

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
