packages:
  - apps/*
  - packages/*
catalog:
  next: 16.0.0
  zod: ^4.1.12
  "@orpc/server": ^1.10.0
  "@orpc/client": ^1.10.0
  "@orpc/openapi": ^1.10.0
  "@orpc/zod": ^1.10.0
  "@prisma/client": ^6.15.0
  better-auth: ^1.3.28
  "@polar-sh/better-auth": ^1.1.3
  dotenv: ^17.2.2
  tsdown: ^0.15.5
