// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "ui": {
    "fields": {
      "images": {
        "dragActiveLabel": "Déposez ici",
        "hint": "ou cliquez pour naviguer",
        "label": "Ajouter des photos",
        "optimizing": "Optimisation des images..."
      },
      "password": {
        "hide": "Cacher le mot de passe",
        "show": "Afficher le mot de passe"
      }
    },
    "languageSwitcher": {
      "ar": "العربية",
      "en": "English",
      "fr": "Français"
    }
  }
}

export default Resources;
