// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "ui": {
    "fields": {
      "password": {
        "hide": "Cacher le mot de passe",
        "show": "Afficher le mot de passe"
      }
    }
  }
}

export default Resources;
