// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "pages": {
    "comingSoon": {
      "button": {
        "label": "Me prevenir",
        "submitting": "Inscription..."
      },
      "description": {
        "line1": "Soyez parmi les premiers informes de notre lancement.",
        "line2": "Des mises a jour exclusives pour les premiers visiteurs."
      },
      "error": "Une erreur est survenue. Veuillez reessayer.",
      "heading": "Lancement imminent",
      "input": {
        "placeholder": "Entrez votre e-mail ou numero de telephone"
      },
      "privacy": "Pas de spam. Seulement les infos de lancement.",
      "success": "Merci ! Nous vous informerons quand nous serons en ligne."
    },
    "description": "Description de la vitrine",
    "store": {
      "cart": {
        "checkout": "Commander",
        "empty": "Votre panier est vide",
        "item": {
          "lowStock": "Il ne reste que {{count}}",
          "outOfStock": "Rupture de stock"
        },
        "title": "Votre panier"
      },
      "categoryFilter": {
        "all": "Tous"
      },
      "checkout": {
        "delivery": {
          "addressFieldset": {
            "description": "Vous pouvez saisir votre adresse manuellement ou utiliser votre position actuelle pour pre-remplir les details de votre adresse.",
            "title": "Adresse de livraison"
          },
          "addressLineDescription": "Nom de rue, quartier ou point de repere - tout ce qui aide le livreur a vous trouver.",
          "city": "Ville",
          "fastDelivery": "Livraison rapide en 24-48 h",
          "fullName": "Nom complet",
          "instructions": "Instructions de livraison",
          "locationErrorDescription": "Autorisez l'acces a la localisation dans votre navigateur (icone cadenas ou info dans la barre d'adresse), ou saisissez votre adresse manuellement.",
          "locationErrorTitle": "Impossible d'obtenir votre position",
          "phone": "Telephone",
          "postalCode": "Code postal",
          "streetAddress": "Ligne d'adresse",
          "title": "Livraison",
          "useLocation": "Utiliser la localisation du telephone",
          "useLocationDescription": "Appuyez pour renseigner le code postal, la ville et la premiere ligne d'adresse lorsque c'est possible.",
          "useLocationPrivacy": "Nous utilisons uniquement votre position GPS approximative. Pas de carte, pas d'adresse exacte.",
          "whatsapp": "Ce numero est sur WhatsApp",
          "whatsappDescription": "Nous pouvons vous joindre plus rapidement sur WhatsApp."
        },
        "error": "Une erreur est survenue. Veuillez reessayer.",
        "orderSummary": {
          "free": "Gratuit",
          "quantity": "Quantite",
          "shipping": "Livraison",
          "subtotal": "Sous-total",
          "title": "Commande",
          "total": "Total"
        },
        "payment": {
          "cod": "Paiement a la livraison (COD)",
          "comingSoon": "Bientot disponible",
          "creditCard": "Carte bancaire",
          "title": "Paiement"
        },
        "placeOrder": "Passer la commande",
        "submitting": "Validation de la commande...",
        "success": {
          "continueShopping": "Continuer vos achats",
          "message": "Merci pour votre commande ! Le marchand recevra votre commande et vous contactera bientot.",
          "title": "Commande creee avec succes"
        },
        "title": "Paiement"
      },
      "filter": {
        "availability": "Disponibilite",
        "button": "Filtrer",
        "cancel": "Annuler",
        "category": "Categorie",
        "drawerTitle": "Filtrer les produits",
        "inStockOnly": "En stock uniquement",
        "max": "Max",
        "min": "Min",
        "price": "Prix",
        "reset": "Reinitialiser",
        "sortBy": "Trier par",
        "sortOptions": {
          "cheapest": "Moins chers d'abord",
          "mostExpensive": "Plus chers d'abord",
          "newest": "Plus recents d'abord"
        },
        "submit": "Valider"
      },
      "footer": {
        "copyright": "Tous droits reserves",
        "poweredBy": "Propulse par Dukkani"
      },
      "owner": {
        "title": "Propriétaire du magasin"
      },
      "product": {
        "addToCart": {
          "button": "Ajouter au panier",
          "outOfStock": "Rupture de stock"
        },
        "description": {
          "label": "Description"
        },
        "imageCarousel": {
          "goToSlide": "Aller a la diapositive {{index}}"
        },
        "quickAdd": {
          "quantity": "Quantite",
          "viewDetails": "Voir tous les details"
        },
        "sizeSelector": {
          "label": "Taille"
        },
        "storeInfo": {
          "closed": "Ferme",
          "openNow": "Ouvert"
        }
      },
      "products": {
        "empty": "Aucun produit disponible pour le moment",
        "title": "Produits"
      }
    },
    "storeSelector": {
      "button": "Voir le magasin",
      "description": "Saisissez le slug du magasin pour voir la vitrine.",
      "errorNotFound": "Magasin introuvable. Veuillez verifier le slug.",
      "errorReserved": "Ce slug est reserve.",
      "heading": "Selectionnez un magasin",
      "loading": "Chargement...",
      "placeholder": "ex. demo, omar-home"
    },
    "title": "Vitrine"
  },
  "ui": {
    "currencies": {
      "DZD": {
        "label": "Dinar algérien",
        "region": "Algérie"
      },
      "EUR": {
        "label": "Euro",
        "region": "Union européenne"
      },
      "GBP": {
        "label": "Livre sterling",
        "region": "Royaume-Uni"
      },
      "LYD": {
        "label": "Dinar libyen",
        "region": "Libye"
      },
      "TND": {
        "label": "Dinar tunisien",
        "region": "Tunisie"
      },
      "USD": {
        "label": "Dollar américain",
        "region": "États-Unis"
      }
    },
    "fields": {
      "images": {
        "dragActiveLabel": "Déposez ici",
        "hint": "ou cliquez pour naviguer",
        "label": "Ajouter des photos",
        "optimizing": "Optimisation des images..."
      },
      "password": {
        "hide": "Cacher le mot de passe",
        "show": "Afficher le mot de passe"
      }
    },
    "languageSwitcher": {
      "ar": "العربية",
      "en": "English",
      "fr": "Français"
    }
  }
}

export default Resources;
