// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "home": {
    "body": {
      "automatedConfirmation": {
        "benefits": ["Économisez des heures d'appels téléphoniques", "Éliminez les commandes fictives", "Vérifiez l'exactitude de l'adresse"],
        "description": "Notre système automatisé appelle le client pour vérifier son sérieux et l'exactitude de l'adresse. Seules les commandes confirmées sont envoyées à la livraison.",
        "eyebrow": "CONFIRMATION AUTOMATISÉE",
        "flowchart": {
          "steps": ["Le client passe commande", "Commande reçue", "Confirmation commencée", "Le système appelle le client", "Adresse vérifiée", "Prêt pour la livraison"],
          "title": "Flux de confirmation de commande"
        },
        "guarantee": {
          "description": "Ne payez pas de frais de livraison pour les commandes fictives.",
          "title": "Garantie zéro risque"
        },
        "title": "Nous confirmons les commandes pour vous."
      },
      "costCalculator": {
        "cta": "Commencez à automatiser aujourd'hui",
        "failedCostLabel": "Coût de livraison échouée (TND)",
        "failedCostSuffix": "TND",
        "fakeOrdersLabel": "Commandes fictives (%)",
        "fakeOrdersSuffix": "%",
        "hoursWastedLabel": "HEURES PERDUES / MOIS",
        "minutesPerCallLabel": "Minutes par appel",
        "minutesPerCallSuffix": "min",
        "moneyLostLabel": "ARGENT PERDU / MOIS",
        "ordersPerDayLabel": "Commandes par jour",
        "ordersPerDaySuffix": "commandes",
        "perMonth": "/ mois",
        "savingsLabel": "ÉCONOMIES ESTIMÉES AVEC DUKKANI",
        "savingsPrefix": "+",
        "title": "Combien coûte le travail manuel ?"
      },
      "cta": {
        "primary": "Créer ma boutique gratuite",
        "subtitle": "Rejoignez des milliers de vendeurs tunisiens qui automatisent leur entreprise.",
        "telegramSupport": "Support Telegram",
        "titleLine1": "Vendez plus.",
        "titleLine2": "Appelez moins."
      },
      "features": {
        "items": {
          "cleanDashboard": {
            "descriptionDesktop": "Voir les commandes, les revenus et l'état de livraison en un seul aperçu simple.",
            "descriptionMobile": "Commandes, revenus et livraisons en un seul aperçu.",
            "title": "Tableau de bord propre"
          },
          "customDomain": {
            "descriptionDesktop": "Connectez votre propre domaine .tn ou .com pour une boutique professionnelle et de marque.",
            "descriptionMobile": "Utilisez votre propre domaine .tn.",
            "title": "Domaine personnalisé"
          },
          "instagramBioLink": {
            "descriptionDesktop": "Lien propre et à forte conversion pour votre bio Instagram et Facebook.",
            "descriptionMobile": "Lien à forte conversion pour la bio.",
            "title": "Lien bio"
          },
          "invoicingReady": {
            "descriptionDesktop": "Exportez les commandes et les paiements proprement pour la comptabilité et les rapports.",
            "descriptionMobile": "Exportation propre pour la comptabilité.",
            "title": "Prêt pour la facturation"
          },
          "massNotify": {
            "descriptionDesktop": "Envoyez des notifications groupées pour des promotions et des mises à jour aux anciens acheteurs.",
            "descriptionMobile": "Envoyez des mises à jour aux anciens acheteurs.",
            "title": "Notifier massivement les clients"
          },
          "recoverOrders": {
            "descriptionDesktop": "Suivez automatiquement les commandes impayées et échouées pour récupérer de l'argent.",
            "descriptionMobile": "Suivi automatique des commandes impayées.",
            "title": "Récupérer les commandes"
          },
          "seoReady": {
            "descriptionDesktop": "Pages rapides et structurées qui aident vos produits à être trouvés.",
            "descriptionMobile": "Structurées pour les moteurs de recherche.",
            "title": "Pages produits prêtes pour le SEO"
          },
          "telegramAlerts": {
            "descriptionDesktop": "Recevez une notification instantanée sur Telegram lorsqu'une nouvelle commande arrive.",
            "descriptionMobile": "Notifications instantanées sur Telegram.",
            "title": "Alertes Telegram"
          },
          "trustDelivery": {
            "descriptionDesktop": "Imprimez des bordereaux et planifiez des ramassages COD en un clic.",
            "descriptionMobile": "Planification de ramassage intégrée.",
            "title": "Trust Delivery"
          }
        },
        "subtitle": "Automatisation conçue pour les vendeurs COD tunisiens.",
        "title": "Tout ce dont vous avez besoin"
      },
      "hero": {
        "badge": "Fait pour la Tunisie 🇹🇳",
        "ctaPrimary": "Créer une boutique gratuite",
        "ctaSecondary": "Voir comment ça fonctionne",
        "subtitle": "Dukkani construit votre boutique, confirme vos commandes en contre-remboursement et prépare la livraison.",
        "titleLine1": "Arrêtez d'appeler",
        "titleLine2": "les clients.",
        "titleLine3": "Commencez à vendre",
        "titleLine4": "automatiquement."
      },
      "painPoints": {
        "items": {
          "fakeOrders": {
            "description": "Les commandes farces vous coûtent de l'argent.",
            "title": "Commandes fictives"
          },
          "lostDms": {
            "description": "Les ventes sont enterrées sous les demandes.",
            "title": "DMs perdus"
          },
          "manualForms": {
            "description": "Écrire des bons de livraison est lent.",
            "title": "Formulaires manuels"
          },
          "wastedTime": {
            "description": "Appeler chaque client prend des heures.",
            "title": "Temps perdu"
          }
        },
        "subtitle": "Vous perdez des heures sur des tâches qui devraient être automatiques.",
        "title": "La vente manuelle est épuisante."
      },
      "process": {
        "steps": {
          "createStore": {
            "descriptionDesktop": "Configurez votre boutique de marque en seulement 5 minutes.",
            "descriptionMobile": "Configuration en 5 minutes.",
            "title": "1. Créer une boutique"
          },
          "deliveryReady": {
            "descriptionDesktop": "Le colis est préparé pour le ramassage par Trust Delivery.",
            "descriptionMobile": "Préparé pour le ramassage.",
            "title": "4. Livraison prête"
          },
          "shareLink": {
            "descriptionDesktop": "Mettez le lien dans votre bio et vos annonces Instagram.",
            "descriptionMobile": "Lien dans la bio et les annonces.",
            "title": "2. Partager le lien"
          },
          "weConfirm": {
            "descriptionDesktop": "Notre système appelle et vérifie la commande automatiquement.",
            "descriptionMobile": "Le système appelle les clients.",
            "title": "3. Nous confirmons"
          }
        },
        "title": "Processus simple en 4 étapes"
      }
    },
    "footer": {
      "brandName": "Dukkani",
      "contact": "Contacter le support",
      "madeForTunisia": "Fait pour la Tunisie",
      "privacy": "Politique de confidentialité",
      "terms": "Conditions d'utilisation"
    },
    "header": {
      "brandName": "Dukkani",
      "features": "Fonctionnalités",
      "pricing": "Tarification",
      "startSelling": "Commencer à vendre"
    }
  }
}

export default Resources;
