// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "ui": {
    "currencies": {
      "DZD": {
        "label": "Dinar algérien",
        "region": {
          "code": "DZ",
          "name": "Algérie"
        }
      },
      "EUR": {
        "label": "Euro",
        "region": {
          "code": "EU",
          "name": "Union européenne"
        }
      },
      "GBP": {
        "label": "Livre sterling",
        "region": {
          "code": "GB",
          "name": "Royaume-Uni"
        }
      },
      "LYD": {
        "label": "Dinar libyen",
        "region": {
          "code": "LY",
          "name": "Libye"
        }
      },
      "TND": {
        "label": "Dinar tunisien",
        "region": {
          "code": "TN",
          "name": "Tunisie"
        }
      },
      "USD": {
        "label": "Dollar américain",
        "region": {
          "code": "US",
          "name": "États-Unis"
        }
      }
    },
    "fields": {
      "images": {
        "dragActiveLabel": "Déposez ici",
        "hint": "ou cliquez pour naviguer",
        "label": "Ajouter des photos",
        "optimizing": "Optimisation des images..."
      },
      "password": {
        "hide": "Cacher le mot de passe",
        "show": "Afficher le mot de passe"
      }
    },
    "languageSwitcher": {
      "ar": "العربية",
      "en": "English",
      "fr": "Français"
    }
  }
}
