// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "pages": {
    "auth": {
      "emailSignIn": {
        "back": "Retour",
        "continue": "Continuer",
        "email": {
          "label": "Adresse e-mail",
          "placeholder": "Entrez votre email"
        },
        "password": {
          "label": "Mot de passe",
          "placeholder": "Entrez votre mot de passe"
        },
        "rememberMe": "Souviens-toi de moi",
        "signIn": "Se connecter"
      }
    },
    "dashboard": {
      "description": "Dashboard description",
      "overview": {
        "quickActions": {
          "addProduct": "Ajouter un nouveau produit",
          "title": "ACTIONS RAPIDES",
          "viewOrders": "Voir toutes les commandes"
        },
        "storeHeader": {
          "liveStore": "Magasin en direct",
          "tapToCopy": "Appuyez pour copier et partager",
          "yourStoreLink": "Votre lien de magasin"
        },
        "thisWeek": {
          "orders": "Commandes",
          "title": "Cette semaine"
        },
        "todaysPerformance": {
          "orders": "Commandes",
          "revenue": "Revenus",
          "title": "PERFORMANCE D'AUJOURD'HUI"
        }
      },
      "storeInitializer": {
        "goToOnboarding": "Aller à l'intégration",
        "loadError": "Impossible de charger vos magasins. Veuillez réessayer.",
        "noStores": "Vous n'avez pas encore de magasin. Créez-en un pour continuer."
      },
      "title": "Dashboard"
    },
    "onboarding": {
      "actions": {
        "retry": "Réessayer"
      },
      "complete": {
        "actions": {
          "addProduct": "Ajouter votre premier produit",
          "goToDashboard": "Aller au tableau de bord"
        },
        "errors": {
          "emailAlreadyInUse": "Un compte avec cet e-mail existe déjà. Veuillez utiliser un autre e-mail ou vous connecter.",
          "storeLoadFailed": "Nous n'avons pas pu charger votre magasin. Actualisez la page ou contactez le support."
        },
        "storeLink": {
          "copied": "Lien copié dans le presse-papiers !",
          "label": "Lien de votre magasin"
        },
        "subtitle": "Votre magasin est prêt à commencer à recevoir des commandes.",
        "telegram": {
          "connectButton": "Connecter",
          "description": "Connectez votre Telegram pour être notifié dès qu'un client passe une commande.",
          "instructions": "Envoyez /link {code} au bot si vous n'êtes pas redirigé.",
          "otpLabel": "Votre code OTP",
          "title": "Alertes de commande instantanées"
        },
        "title": "Tout est prêt !"
      },
      "signup": {
        "agreeText": "En continuant, vous acceptez nos",
        "alreadyHaveAccount": "Vous avez déjà un compte ?",
        "and": "et",
        "email": {
          "description": "Nous avons prérempli ce champ à partir de l'étape précédente",
          "existsError": "L'email existe déjà. Veuillez utiliser un autre email.",
          "label": "Adresse e-mail",
          "missingWarning": "L'adresse e-mail n'a pas été fournie. Veuillez entrer votre adresse e-mail pour continuer.",
          "placeholder": "votre@email.com",
          "readonlyHint": "L'email fourni dans l'URL ne peut pas être modifié",
          "validating": "Vérification de la disponibilité de l'email..."
        },
        "login": "Se connecter",
        "name": {
          "label": "Comment devrions-nous vous appeler ?",
          "placeholder": "Entrez votre nom complet"
        },
        "password": {
          "label": "Choisissez un mot de passe",
          "placeholder": "Minimum 8 caractères"
        },
        "privacy": "Politique de confidentialité",
        "submit": "Continuer vers la configuration du magasin",
        "subtitle": "Rejoignez Dukkani et commencez à vendre dès aujourd'hui",
        "terms": "Conditions",
        "title": "Créez votre compte"
      },
      "steps": {
        "complete": "Prêt",
        "signup": "Compte",
        "storeConfiguration": "Configurer",
        "storeSetup": "Magasin"
      },
      "storeConfiguration": {
        "category": {
          "label": "Quelle catégorie décrit le mieux votre magasin ?",
          "options": {
            "beauty": {
              "description": "Cosmétiques et soins personnels",
              "label": "Beauté"
            },
            "books": {
              "description": "Livres et matériel de lecture",
              "label": "Livres"
            },
            "electronics": {
              "description": "Gadgets, appareils et technologie",
              "label": "Électronique"
            },
            "fashion": {
              "description": "Vêtements, accessoires et style",
              "label": "Mode"
            },
            "food": {
              "description": "Produits alimentaires et boissons",
              "label": "Alimentation"
            },
            "home": {
              "description": "Décoration et essentiels pour la maison",
              "label": "Maison"
            },
            "other": {
              "description": "Autres catégories",
              "label": "Autre"
            },
            "sports": {
              "description": "Équipement et matériel de sport",
              "label": "Sports"
            },
            "toys": {
              "description": "Jouets et jeux",
              "label": "Jouets"
            }
          }
        },
        "submit": "Terminer la configuration",
        "subtitle": "Personnalisez l'apparence et la catégorie de votre magasin",
        "theme": {
          "label": "Choisissez le thème de votre magasin",
          "options": {
            "classic": {
              "description": "Style intemporel",
              "label": "Classique"
            },
            "dark": {
              "description": "Moderne et élégant",
              "label": "Sombre"
            },
            "light": {
              "description": "Propre et lumineux",
              "label": "Clair"
            },
            "minimal": {
              "description": "Simple et élégant",
              "label": "Minimal"
            },
            "modern": {
              "description": "Design contemporain",
              "label": "Moderne"
            }
          }
        },
        "title": "Configurez votre magasin"
      },
      "storeSetup": {
        "currency": {
          "label": "Devise du magasin",
          "placeholder": "Sélectionnez la devise de votre magasin"
        },
        "notifications": {
          "label": "Comment souhaitez-vous recevoir les alertes de nouvelles commandes ?",
          "options": {
            "both": {
              "description": "Soyez notifié partout pour ne jamais manquer une commande",
              "label": "Les deux"
            },
            "email": {
              "description": "Envoyées à votre adresse e-mail de connexion",
              "label": "Notifications par e-mail"
            },
            "telegram": {
              "description": "Alertes rapides et instantanées via notre bot Telegram",
              "label": "Alertes Telegram"
            }
          }
        },
        "storeName": {
          "label": "Nom du magasin",
          "placeholder": "Mon Super Magasin"
        },
        "submit": "Continuer",
        "subtitle": "Plus qu'une étape pour commencer",
        "title": "Créez votre magasin"
      }
    },
    "orders": {
      "list": {
        "advanceStatus": "Avancer",
        "call": "Appeler",
        "card": "Carte",
        "cashOnDelivery": "Paiement à la livraison",
        "description": "Voir et gérer les commandes",
        "empty": "Aucune commande trouvée. Les commandes apparaîtront ici une fois que les clients commenceront à les passer.",
        "error": "Erreur de chargement des commandes. Veuillez réessayer plus tard.",
        "filterDrawer": {
          "apply": "Appliquer les filtres",
          "clearAll": "Tout effacer",
          "dateRange": "Plage de dates",
          "from": "De",
          "pickDateRange": "Choisir une plage de dates",
          "status": "Statut",
          "title": "Filtrer les commandes",
          "to": "À"
        },
        "filters": {
          "all": "Tout",
          "cancelled": "Annulé",
          "confirmed": "Confirmé",
          "delivered": "Livré",
          "pending": "En attente",
          "processing": "En traitement",
          "shipped": "Expédié"
        },
        "itemsCount": "{count} articles",
        "refresh": "Rafraîchir les commandes",
        "searchPlaceholder": "Rechercher par nom, téléphone ou numéro de commande #",
        "status": {
          "cancelled": "Annulé",
          "confirmed": "Confirmé",
          "delivered": "Livré",
          "pending": "En attente de confirmation",
          "processing": "En traitement",
          "shipped": "Expédié"
        },
        "title": "Commandes",
        "today": "Aujourd'hui",
        "viewOrder": "Voir la commande {id}",
        "yesterday": "Hier"
      }
    },
    "products": {
      "create": {
        "form": {
          "cancel": "Annuler",
          "category": {
            "create": "Créer une catégorie",
            "createDescription": "Créez une nouvelle catégorie pour organiser vos produits.",
            "created": "Catégorie créée avec succès",
            "label": "Catégorie",
            "nameLabel": "Nom de la catégorie",
            "namePlaceholder": "p. ex. T-Shirts, Électronique",
            "noResults": "Aucune catégorie trouvée.",
            "placeholder": "Sélectionnez une catégorie...",
            "searchPlaceholder": "Rechercher des catégories...",
            "uncategorized": "Non classé"
          },
          "description": {
            "label": "Description",
            "placeholder": "Entrez la description du produit"
          },
          "name": {
            "label": "Nom du produit",
            "placeholder": "Entrez le nom du produit"
          },
          "optional": "optionnel",
          "options": {
            "description": "Ajoutez des options comme Taille, Couleur, Matériau, etc.",
            "label": "A des options"
          },
          "photos": "Photos",
          "price": {
            "label": "Prix",
            "placeholder": "Entrez le prix du produit"
          },
          "priceHelp": "Prix que les clients paient (COD)",
          "published": {
            "label": "Publié",
            "placeholder": "Entrez le produit publié"
          },
          "saveDraft": "Enregistrer le brouillon",
          "savePublish": "Enregistrer et publier",
          "stock": {
            "label": "Stock",
            "placeholder": "Entrez le stock du produit"
          },
          "validation": {
            "errors": "Veuillez corriger les erreurs du formulaire avant de soumettre"
          },
          "variants": {
            "edit": {
              "price": "Prix",
              "priceHelp": "Laissez vide pour utiliser le prix de base du produit",
              "sku": "SKU",
              "skuPlaceholder": "Optionnel",
              "stock": "Stock",
              "title": "Modifier la variante"
            },
            "list": {
              "edit": "Modifier la variante",
              "empty": "Ajoutez des options de variante ci-dessus pour générer des variantes",
              "price": "Prix",
              "stock": "Stock",
              "title": "Variantes",
              "unnamed": "Variante sans nom"
            },
            "options": {
              "add": "Ajouter une option",
              "addAnother": "Ajouter une option",
              "addValue": "Ajouter une valeur",
              "empty": "Ajoutez des options comme Taille, Couleur, Matériau, etc.",
              "noValues": "Ajoutez au moins une valeur",
              "optionName": "Nom de l'option",
              "optionNamePlaceholder": "p. ex. Taille, Couleur",
              "remove": "Supprimer l'option",
              "title": "Options de variante",
              "unnamed": "Option sans nom",
              "value": "Valeur",
              "values": "Valeurs"
            },
            "validation": {
              "duplicateOption": "Option dupliquée",
              "duplicateOptionName": "Nom d'option dupliqué",
              "duplicateOptionValues": "Valeurs d'option dupliquées",
              "duplicateValue": "Valeur dupliquée"
            }
          }
        },
        "header": {
          "save": "Enregistrer",
          "title": "Nouveau produit"
        },
        "noStore": {
          "createStore": "Créer un magasin",
          "description": "Veuillez d'abord créer un magasin pour ajouter des produits.",
          "title": "Aucun magasin trouvé"
        },
        "sections": {
          "essentials": "Essentiels",
          "options": "A des options",
          "organization": "Organisation",
          "photos": "Photos du produit"
        },
        "success": "Produit créé avec succès !"
      },
      "list": {
        "actions": {
          "archive": "Archiver",
          "cancel": "Annuler",
          "delete": "Supprimer",
          "deleteConfirmDescription": "Cette action ne peut pas être annulée.",
          "deleteConfirmTitle": "Supprimer le produit ?",
          "edit": "Modifier",
          "publish": "Publier",
          "unpublish": "Dépublier"
        },
        "addProduct": "Ajouter un produit",
        "catalogCount": "Votre catalogue de produits ({count} au total)",
        "catalogDefault": "Votre catalogue de produits",
        "description": "Gérez vos produits",
        "empty": "Aucun produit trouvé. Créez votre premier produit pour commencer.",
        "error": "Erreur de chargement des produits. Veuillez réessayer plus tard.",
        "filterDrawer": {
          "all": "Tous les statuts",
          "allInventory": "Tous",
          "allProducts": "Tous les produits",
          "allStatuses": "Tous les statuts",
          "apply": "Appliquer les filtres",
          "clearAll": "Tout effacer",
          "close": "Fermer",
          "draft": "Brouillon",
          "inStock": "En stock",
          "inventory": "Inventaire",
          "lowStock": "Stock faible",
          "max": "Max",
          "min": "Min",
          "outOfStock": "Rupture de stock",
          "priceRange": "Plage de prix (TND)",
          "published": "Publié",
          "singleSku": "SKU unique",
          "status": "Statut",
          "title": "Filtres",
          "variants": "Variantes",
          "withVariants": "Avec variantes"
        },
        "filters": {
          "all": "Tous",
          "archived": "Archivé",
          "draft": "Brouillon",
          "published": "Publié"
        },
        "noVariants": "• Pas de variantes",
        "outOfStock": "Rupture de stock",
        "outOfStockVariants": "Rupture de stock • {variants} variantes",
        "searchPlaceholder": "Rechercher des produits",
        "status": {
          "archived": "Archivé",
          "draft": "Brouillon",
          "published": "Publié"
        },
        "stockCount": "Stock : {count} unités",
        "stockInfo": "Stock : {count} unités • {variants} variantes",
        "stockInfoNoVariants": "Stock : {count} unités • Pas de variantes",
        "title": "Produits",
        "variantCount": "• {variants} variantes"
      }
    },
    "settings": {
      "telegram": {
        "cancelButton": "Annuler",
        "description": "Liez votre compte Telegram pour recevoir des notifications de commande instantanées",
        "disconnectButton": "Déconnecter Telegram",
        "disconnectDescription": "Pour confirmer la déconnexion, veuillez entrer le nom de l'une de vos boutiques :",
        "disconnectError": "Le nom de la boutique ne correspond pas. Veuillez réessayer.",
        "disconnectNotLinked": "Le compte Telegram n'est pas lié",
        "disconnectPlaceholder": "Entrer le nom de la boutique",
        "disconnectSuccess": "Compte Telegram déconnecté avec succès",
        "disconnectTitle": "Déconnecter le compte Telegram",
        "error": "Une erreur est survenue. Veuillez réessayer.",
        "expires": "Ce lien expire dans 10 minutes. Si Telegram n'est pas installé, vous pouvez l'installer depuis",
        "linkButton": "Lier via Telegram",
        "linked": "Compte Telegram lié le",
        "option1": "Option 1 : Cliquez sur le lien ci-dessous",
        "option2": "Option 2 : Scannez le code QR",
        "otpCode": "Code OTP",
        "recently": "récemment",
        "storeNameLabel": "Nom de la boutique",
        "storeNameRequired": "Le nom de la boutique est requis",
        "title": "Notifications Telegram",
        "yourStores": "Vos boutiques :"
      }
    }
  }
}

export default Resources;
