/**
 * Helper to create runtimeEnv object for Next.js presets
 * MUST use literal property access (not loops) for Next.js bundling to work
 */
export function createNextjsRuntimeEnv() {
	return {
		// Base server vars
		NODE_ENV: process.env.NODE_ENV,
		CORS_PREVIEW_ORIGIN_PATTERN: process.env.CORS_PREVIEW_ORIGIN_PATTERN,
		// Base client vars - MUST be literal, or Next won't inline
		NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
		NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
		NEXT_PUBLIC_ALLOWED_ORIGIN: process.env.NEXT_PUBLIC_ALLOWED_ORIGIN,
		// URLs module vars
		NEXT_PUBLIC_WEB_URL: process.env.NEXT_PUBLIC_WEB_URL,
		NEXT_PUBLIC_DASHBOARD_URL: process.env.NEXT_PUBLIC_DASHBOARD_URL,
		NEXT_PUBLIC_STORE_DOMAIN: process.env.NEXT_PUBLIC_STORE_DOMAIN,
		// Vercel server vars
		VERCEL_ENV: process.env.VERCEL_ENV,
		VERCEL_TARGET_ENV: process.env.VERCEL_TARGET_ENV,
		VERCEL_URL: process.env.VERCEL_URL,
		VERCEL_BRANCH_URL: process.env.VERCEL_BRANCH_URL,
		VERCEL_PROJECT_PRODUCTION_URL: process.env.VERCEL_PROJECT_PRODUCTION_URL,
		VERCEL_REGION: process.env.VERCEL_REGION,
		VERCEL_DEPLOYMENT_ID: process.env.VERCEL_DEPLOYMENT_ID,
		VERCEL_PROJECT_ID: process.env.VERCEL_PROJECT_ID,
		VERCEL_SKEW_PROTECTION_ENABLED: process.env.VERCEL_SKEW_PROTECTION_ENABLED,
		VERCEL_AUTOMATION_BYPASS_SECRET:
			process.env.VERCEL_AUTOMATION_BYPASS_SECRET,
		VERCEL_OIDC_TOKEN: process.env.VERCEL_OIDC_TOKEN,
		VERCEL_GIT_PROVIDER: process.env.VERCEL_GIT_PROVIDER,
		VERCEL_GIT_REPO_SLUG: process.env.VERCEL_GIT_REPO_SLUG,
		VERCEL_GIT_REPO_OWNER: process.env.VERCEL_GIT_REPO_OWNER,
		VERCEL_GIT_REPO_ID: process.env.VERCEL_GIT_REPO_ID,
		VERCEL_GIT_COMMIT_REF: process.env.VERCEL_GIT_COMMIT_REF,
		VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
		VERCEL_GIT_COMMIT_MESSAGE: process.env.VERCEL_GIT_COMMIT_MESSAGE,
		VERCEL_GIT_COMMIT_AUTHOR_LOGIN: process.env.VERCEL_GIT_COMMIT_AUTHOR_LOGIN,
		VERCEL_GIT_COMMIT_AUTHOR_NAME: process.env.VERCEL_GIT_COMMIT_AUTHOR_NAME,
		VERCEL_GIT_PREVIOUS_SHA: process.env.VERCEL_GIT_PREVIOUS_SHA,
		VERCEL_GIT_PULL_REQUEST_ID: process.env.VERCEL_GIT_PULL_REQUEST_ID,
		VERCEL: process.env.VERCEL,
		// Database vars
		DATABASE_URL: process.env.DATABASE_URL,
		// Telegram vars
		TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
		TELEGRAM_BOT_NAME: process.env.TELEGRAM_BOT_NAME,
		TELEGRAM_API_TOKEN: process.env.TELEGRAM_API_TOKEN,
		TELEGRAM_WEBHOOK_SECRET: process.env.TELEGRAM_WEBHOOK_SECRET,
		// Storage vars
		STORAGE_ENDPOINT: process.env.STORAGE_ENDPOINT,
		STORAGE_REGION: process.env.STORAGE_REGION,
		STORAGE_BUCKET: process.env.STORAGE_BUCKET,
		STORAGE_ACCESS_KEY_ID: process.env.STORAGE_ACCESS_KEY_ID,
		STORAGE_SECRET_ACCESS_KEY: process.env.STORAGE_SECRET_ACCESS_KEY,
		STORAGE_PUBLIC_URL: process.env.STORAGE_PUBLIC_URL,
		// S3 storage module vars
		S3_ENDPOINT: process.env.S3_ENDPOINT,
		S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
		S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
		S3_BUCKET: process.env.S3_BUCKET,
		S3_PUBLIC_BASE_URL: process.env.S3_PUBLIC_BASE_URL,
		S3_REGION: process.env.S3_REGION,
		STORAGE_PREVIEW_PREFIX: process.env.STORAGE_PREVIEW_PREFIX,
		STORAGE_MAX_FILE_SIZE: process.env.STORAGE_MAX_FILE_SIZE,
		STORAGE_ALLOWED_MIME_TYPES: process.env.STORAGE_ALLOWED_MIME_TYPES,
		SUPABASE_URL: process.env.SUPABASE_URL,
		SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
		SUPABASE_STORAGE_BUCKET_NAME: process.env.SUPABASE_STORAGE_BUCKET_NAME,
		// Observability server vars - only available on server side
		OTEL_SERVICE_NAME: process.env.OTEL_SERVICE_NAME,
		OTEL_SAMPLING_RATE: process.env.OTEL_SAMPLING_RATE,
		OTEL_ENABLED: process.env.OTEL_ENABLED,
		OTEL_EXPORTER_OTLP_ENDPOINT: process.env.OTEL_EXPORTER_OTLP_ENDPOINT,
		OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
			process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
		OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:
			process.env.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT,
		OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:
			process.env.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT,
		OTEL_EXPORTER_OTLP_HEADERS: process.env.OTEL_EXPORTER_OTLP_HEADERS,
		OTEL_EXPORTER_OTLP_PROTOCOL: process.env.OTEL_EXPORTER_OTLP_PROTOCOL,
		OTEL_EXPORTER_OTLP_COMPRESSION: process.env.OTEL_EXPORTER_OTLP_COMPRESSION,
	} as const;
}
